version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
      - npm install -g pkg
  build:
    commands:
      - npm run build
artifacts:
  files:
    - my-node-app
  discard-paths: yes
